name: 'Fe2O3'
species_types: ['electron', 'hole']
species_charge_list:
    'full': [-1, +1]
    'partial': [-0.5, +0.5]
species_to_element_type_map:
    'electron': ['Fe']
    'hole': ['O']
# multiples of elementary charge
charge_types:
    'full':
        'Fe': +3.0
        'O': -2.0
    'partial':
        'Fe': +1.6349
        'O': -1.0899
neighbor_cutoff_dist:
    'Fe:Fe': [[2.971, 2.901]]
neighbor_cutoff_dist_tol:
    'Fe:Fe': [[0.0020, 0.0020]]
# Source: Kerisit et al., GCA 2006. DOI: 10.1016/j.gca.2005.12.021
vn: 1.85E+13  # typical frequency for nuclear motion in (1/sec)
# reorganization energy in eV
lambda_values:
    'Fe:Fe': [[1.74533, 1.88683]]
# electronic coupling matrix element in eV
v_ab:
    'Fe:Fe': [[0.184, 0.028]]
class_list:
    'Fe': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    'O': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
element_type_delimiter: ':'
# Direction-averaged value of the static dielectric constant of the potential 
# model used in KMC paper. Dielectric constant tensor obtained from METADISE.
# Source: Kerisit et al., The Journal of Chemical Physics 127, 124706 (2007); 
# DOI: 10.1063/1.2768522
dielectric_constant: 9.355

# Ewald parameters
# alpha: 'optimal' or <float>
# r_cut: 'optimal' or 'simulation_cell' or <float>
# k_cut: 'optimal' or <float>
alpha: 2.667e-01
r_cut: 4.618e+00
k_cut: 6.998e+00

precision_parameters:
    lower_bound_real: 0.7500
    lower_bound_rcut: 0.0000
    upper_bound_rcut: 0.9999
    lower_bound_kcut: 0.0000
    upper_bound_kcut: 10.0000
    threshold_fraction: 0.9000
    precise_r_cut: 0
    # err_tol = 0.1 kBT in eV
    err_tol: 2.585e-03
    step_increase_tol: 2.585e-10
    num_data_points_low: 1.000e+01
    num_data_points_high: 5.000e+01
    step_change_data_points: 1.000e+01

# Coordinates source:
# http://rruff.geo.arizona.edu/AMS/download.php?id=00230.cif&down=cif
# Source article:
# Blake, R. L., et al. "Refinement of hematite structure."
# American Mineralogist 51.1-2 (1966): 123-129.

